[versions]
config4k = "0.4.2"
coroutines = "1.6.0"
junit = "5.8.2"
kotlin = "1.6.10"
ktor = "2.0.0-beta-1"
logback = "1.2.10"
mapdb = "3.0.8"
micrometer = "1.8.2"
mockk = "1.12.2"
serialization = "1.3.2"
slf4j = "1.7.33"

[libraries]
config4k = { module = "io.github.config4k:config4k", version.ref = "config4k" }

junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-content-negation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-client = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }

logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

mapdb = { module = "org.mapdb:mapdb", version.ref = "mapdb" }

micrometer-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "micrometer" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
